version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      python-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    groups:
      frontend-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      backend-container-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    groups:
      frontend-container-minor-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
